normalize_doc_attributes = true
normalize_comments = true
wrap_comments = true
comment_width = 100

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Mixed"
reorder_imports = true
reorder_modules = true

reorder_impl_items = true

struct_lit_single_line = true
overflow_delimited_expr = true
match_block_trailing_comma = true
format_macro_matchers = true
format_macro_bodies = true
condense_wildcard_suffixes = true
trailing_semicolon = true
newline_style = "Unix"
use_small_heuristics = "Max"
format_strings = true
use_field_init_shorthand = true
